trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArchitecture: 'x64'
    platform: 'Any CPU'
    configuration: 'release'
    restoreNugetPackages: true
    logProjectEvents: true
    createLogFile: true

- script: dotnet test --configuration Debug --no-build
  displayName: 'dotnet tests $(buildConfiguration)'
