//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NugetAnalyzer.BLL.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EndpointPackageMetadata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EndpointPackageMetadata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NugetAnalyzer.BLL.Test.EndpointPackageMetadata", typeof(EndpointPackageMetadata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;https://api.nuget.org/v3/registration3/nunit/3.9.0.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;Package&quot;,
        ///    &quot;http://schema.nuget.org/catalog#Permalink&quot;
        ///  ],
        ///  &quot;catalogEntry&quot;: &quot;https://api.nuget.org/v3/catalog0/data/2018.10.16.12.57.01/nunit.3.9.0.json&quot;,
        ///  &quot;listed&quot;: true,
        ///  &quot;packageContent&quot;: &quot;https://api.nuget.org/v3-flatcontainer/nunit/3.9.0/nunit.3.9.0.nupkg&quot;,
        ///  &quot;published&quot;: &quot;&quot;,
        ///  &quot;registration&quot;: &quot;https://api.nuget.org/v3/registration3/nunit/index.json&quot;,
        ///  &quot;@context&quot;: {
        ///    &quot;@vocab&quot;: &quot;http://schema.n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DateFormatIncorrectResponse {
            get {
                return ResourceManager.GetString("DateFormatIncorrectResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Error&gt;
        ///  &lt;Code&gt;BlobNotFound&lt;/Code&gt;
        ///  &lt;Message&gt;
        ///    The specified blob does not exist.
        ///    RequestId:902b74ab-e01e-0029-2d58-034617000000
        ///    Time:2019-05-05T15:40:52.0412981Z
        ///  &lt;/Message&gt;
        ///&lt;/Error&gt;
        ///.
        /// </summary>
        internal static string NotFoundResponse {
            get {
                return ResourceManager.GetString("NotFoundResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;https://api.nuget.org/v3/registration3/nunit/3.9.0.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;Package&quot;,
        ///    &quot;http://schema.nuget.org/catalog#Permalink&quot;
        ///  ],
        ///  &quot;catalogEntry&quot;: &quot;https://api.nuget.org/v3/catalog0/data/2018.10.16.12.57.01/nunit.3.9.0.json&quot;,
        ///  &quot;listed&quot;: true,
        ///  &quot;packageContent&quot;: &quot;https://api.nuget.org/v3-flatcontainer/nunit/3.9.0/nunit.3.9.0.nupkg&quot;,
        ///  &quot;published&quot;: &quot;2017-11-10T23:35:19.67+00:00&quot;,
        ///  &quot;registration&quot;: &quot;https://api.nuget.org/v3/registration3/nunit/index.json&quot;,
        ///  &quot;@context&quot;: {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUnitResponse {
            get {
                return ResourceManager.GetString("NUnitResponse", resourceCulture);
            }
        }
    }
}
