//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NugetAnalyzer.BLL.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EndpointSearch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EndpointSearch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NugetAnalyzer.BLL.Test.EndpointSearch", typeof(EndpointSearch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@context&quot;: {
        ///    &quot;@vocab&quot;: &quot;http://schema.nuget.org/schema#&quot;,
        ///    &quot;@base&quot;: &quot;https://api.nuget.org/v3/registration3/&quot;
        ///  },
        ///  &quot;totalHits&quot;: 1,
        ///  &quot;lastReopen&quot;: &quot;2019-05-05T15:09:52.5606034Z&quot;,
        ///  &quot;index&quot;: &quot;v3-lucene2-v2v3-20180914&quot;,
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;@id&quot;: &quot;https://api.nuget.org/v3/registration3/test/index.json&quot;,
        ///      &quot;@type&quot;: &quot;Package&quot;,
        ///      &quot;registration&quot;: &quot;https://api.nuget.org/v3/registration3/test/index.json&quot;,
        ///      &quot;id&quot;: &quot;NUnit&quot;,
        ///      &quot;version&quot;: &quot;beta&quot;,
        ///      &quot;title&quot;: &quot;Test&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IncorrectVersionResponse {
            get {
                return ResourceManager.GetString("IncorrectVersionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@context&quot;: {
        ///    &quot;@vocab&quot;: &quot;http://schema.nuget.org/schema#&quot;,
        ///    &quot;@base&quot;: &quot;https://api.nuget.org/v3/registration3/&quot;
        ///  },
        ///  &quot;totalHits&quot;: 0,
        ///  &quot;lastReopen&quot;: &quot;2019-05-05T14:43:52.0630317Z&quot;,
        ///  &quot;index&quot;: &quot;v3-lucene2-v2v3-20180914&quot;,
        ///  &quot;data&quot;: []
        ///}.
        /// </summary>
        internal static string NotExistPackageResponse {
            get {
                return ResourceManager.GetString("NotExistPackageResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@context&quot;: {
        ///    &quot;@vocab&quot;: &quot;http://schema.nuget.org/schema#&quot;,
        ///    &quot;@base&quot;: &quot;https://api.nuget.org/v3/registration3/&quot;
        ///  },
        ///  &quot;totalHits&quot;: 1,
        ///  &quot;lastReopen&quot;: &quot;2019-05-04T21:53:58.3263595Z&quot;,
        ///  &quot;index&quot;: &quot;v3-lucene2-v2v3-20180914&quot;,
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;@id&quot;: &quot;https://api.nuget.org/v3/registration3/nunit/index.json&quot;,
        ///      &quot;@type&quot;: &quot;Package&quot;,
        ///      &quot;registration&quot;: &quot;https://api.nuget.org/v3/registration3/nunit/index.json&quot;,
        ///      &quot;id&quot;: &quot;NUnit&quot;,
        ///      &quot;version&quot;: &quot;3.11.0&quot;,
        ///      &quot;description&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUnitResponse {
            get {
                return ResourceManager.GetString("NUnitResponse", resourceCulture);
            }
        }
    }
}
